name: Udirectory
description: FOR IIT MEMBERS.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.13.0-190.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  parse_server_sdk_flutter: ^3.1.3
  image_picker: ^0.8.5+3
  swipable_stack: ^2.0.0
  intl: ^0.17.0
  google_fonts: ^4.0.4
  material_design_icons_flutter: ^7.0.7296
  flutter_form_builder: ^8.0.0
  flutter_typeahead: ^4.6.1
  modal_bottom_sheet: ^1.0.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/